# replace "my_project" with the name that matches the project name in step 6.
spotipy_wrapped:
  outputs:
    dev:
      type: duckdb
      path: md:spotify_wrapped_extract
      threads: 1
  target: dev
